# Site settings
title: Veracity Lab
email: veracity@vuw.ac.nz
description: To explore, promote and support a high integrity national digital future
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
author:
street_address: RH339, Rutherford House, Pipitea
city: Wellington
state: 
zip_code: 6011
country: New Zealand
phone: +64 (0)27 2888 618

# icon: fa-diamond # Font Awesome class for your site's icon
# icon: fa-500px # Font Awesome class for your site's icon
icon: fa-angle-double-down # Font Awesome class for your site's icon

# Social settings
facebook_url:
# github_url: https://github.com/veracitylab/
gitlab_url: 
googleplus_url:
instagram_url:
# linkedin_url: https://linkedin.com/in/markus-luczak-roesch-81ba5611
pinterest_url:
slack_url:
twitter_url: https://twitter.com/VeracityLab 

# Build settings
markdown: kramdown

# plugins:
  # - jekyll-seo-tag

sass:
style: compressed


# markus.luczak-roesch@vuw.ac.nz